openapi: 3.0.0
info:
  title: Game Release View API
  version: 0.0.1
servers:
  - url: http://localhost/api/v1
paths:
  /releases:
    get:
      summary: returns game releases
      parameters:
        - in: query
          name: from
          schema:
            type: string
            format: date
        - in: query
          name: to
          schema:
            type: string
            format: date
      responses:
        '200':
          description: void
          content:
            application/json:
              schema:
                type: object
                properties:
                  releases:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        date_from:
                          type: string
                          format: date
                        date_to:
                          type: string
                          format: date


