openapi: 3.0.0
info:
  title: Game Release View API
  version: 0.0.1
servers:
  - url: http://localhost/api/v1
paths:
  /releases:
    get:
      summary: returns game releases
      parameters:
        - in: query
          name: from
          schema:
            type: string
            format: date
        - in: query
          name: to
          schema:
            type: string
            format: date
        - in: query
          name: with_unknown
          schema:
            type: boolean
        - in: query
          name: exact_dates_only
          schema:
            type: boolean
      responses:
        '200':
          description: void
          content:
            application/json:
              schema:
                type: object
                properties:
                  releases:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          format: int64
                        name:
                          type: string
                        date_from:
                          type: string
                          format: date
                        date_to:
                          type: string
                          format: date
                        unknown_release_date:
                          type: boolean
                        original_release_string:
                          type: string
                        short_description:
                          type: string
                        filter_attrs:
                          type: object
                          properties:
                            required_age:
                              type: integer
                              format: int64
                            spoken_languages:
                              type: array
                              items:
                                type: string
                            ui_languages:
                              type: array
                              items:
                                type: string
                            subtitle_languages:
                              type: array
                              items:
                                type: string
                            developers:
                              type: array
                              items:
                                type: string
                            publishers:
                              type: array
                              items:
                                type: string
                            categories:
                              type: array
                              items:
                                type: string
                            genres:
                              type: array
                              items:
                                type: string
                        primary_image:
                          type: string
                        website:
                          type: string
                        background_image:
                          type: string
                        shop_url:
                          type: string


